- hosts: localhost
  gather_facts: no
  roles:
    - role: launch
      name: win

- hosts: win
  roles:
    - deploy

- hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - build-ami
    - terminate


