- name: Create AMI
  ec2_ami:
    region: "{{ target_aws_region }}"
    instance_id: "{{ item.id }}"
    name: "windows-personalizado"
    wait: yes
    state: present
  with_items: "{{ ec2_result.tagged_instances }}"
  register: ami

- name: Set New AMI id variable
  set_fact:
    ami_result: "{{ (ami.results | first).image_id  }}"