- name: ensure instances are not running
  ec2:
    region: "{{ target_aws_region }}"
    image: "{{ win_ami_id }}"
    instance_type: "{{ instance_type }}"
    group_id: "{{ sg_out.group_id }}"
    key_name: "{{ keypair }}"
    wait: yes
    wait_timeout: 500
    exact_count: 0
    assign_public_ip: yes
    vpc_subnet_id: "{{ subnet }}"
    count_tag:
      Name: stock-win-ami-test
    instance_tags:
      Name: stock-win-ami-test
  register: ec2_result